FROM debian:trixie-slim

# Install build essential tools to include GCC
RUN apt update && \
    apt install -y  build-essential && \
    apt clean && \
    rm -rf /var/lib/apt/lists/*

# Compile the executable from some C source
WORKDIR /usr/src/app
COPY hello-world.c ./
RUN gcc -static -o hello-world hello-world.c

# Start the executable!
CMD ["/usr/src/app/hello-world"]
